In [2]:
import os
import pandas as pd

In [ ]:
df_clientes = pd.read_csv(r'C:\Users\João Victor\Desktop\sales-etl-pipeline\data\raw\clientes.csv')
df_vendas = pd.read_csv(r'C:\Users\João Victor\Desktop\sales-etl-pipeline\data\raw\vendas.csv') 
df_produtos = pd.read_csv(r'C:\Users\João Victor\Desktop\sales-etl-pipeline\data\raw\produtos.csv')

In [27]:
display(df_clientes)

    id_cliente             nome          cidade estado
0          101       João Silva       São Paulo     SP
1          102      Maria Souza  Rio de Janeiro     RJ
2          103    Pedro Santos         Curitiba     PR
3          104  Carlos Oliveira       São Paulo     sp
4          105         Ana Lima  Belo Horizonte     MG
5          106    Mariana Costa  Rio de Janeiro     RJ
6          107       João Silva       São Paulo     SP
7          108    Lucas Pereira    Porto Alegre     RS
8          109   Fernanda Alves             NaN     SP
9          110       Bruno Lima       São Paulo     SP
10         111    Camila Mendes        Curitiba     Pr
11         112              NaN  Rio de Janeiro     RJ
12         113     Renato Souza       São Paulo     SP

In [ ]:
display(df_vendas)

In [29]:
display(df_produtos)

   id_produto          nome_produto    categoria     marca
0          10              Notebook  Eletrônicos      Dell
1          20                 Mouse   Acessórios  Logitech
2          30               Teclado   acessorios  Logitech
3          40         Cadeira Gamer       Móveis    Pichau
4          50               Monitor  Eletronicos   Samsung
5          60            Smartphone  Eletrônicos   Samsung
6         999  Produto Desconhecido          NaN